import { ChatProvider } from '@nexo-labs/chat-agent'
import type React from 'react'
import { FloatingChatWrapper } from '@/components/organisms/floating-chat-wrapper'
import { UserProvider } from '@/components/organisms/user-context'
import { SEARCH_COLLECTIONS } from '@/payload/plugins/typesense'
import './index.css'

const baseClass = 'multi-tenant'

export const metadata = {
  description: 'Generated by Next',
  title: 'Next'
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={baseClass} lang="en">
      <body>
        <UserProvider>
          <ChatProvider searchCollections={SEARCH_COLLECTIONS}>
            {children}
            <FloatingChatWrapper />
          </ChatProvider>
        </UserProvider>
      </body>
    </html>
  )
}
